### ISSUE TITLE
Is there a good old JAR file I can just use?

### ISSUE THREAD

**Issue by cope** [jwtk/jjwt#127]
Please?

**Comment by lhazlewood** [comment]
The overwhelming majority of the Java world uses Maven or Gradle or even Ant+Ivy and these tools all acquire the necessary dependencies for you.  The days of manually downloading .jar files - specifically because of the complexities of dependency management and version resolution - is gone.  Please use one of these tools in your project to use JJWT.

That said, here is the fastest way to get the jars (with runtime dependencies) manually:

1. git clone https://github.com/jwtk/jjwt.git
1. cd jjwt
1. mvn install -DskipTests
1. mvn dependency:copy-dependencies -DincludeScope=runtime
1. cd target/dependency

All the .jars you need will be in the `target/dependency` folder.

**Comment by cope** [comment]
I am getting a build failure for `mvn install -DskipTests`:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.646 s
[INFO] Finished at: 2016-06-01T11:12:11+02:00
[INFO] Final Memory: 27M/312M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:cobertura-maven-plugin:2.7:check (default) on project jjwt: Coverage check failed. See messages above. -> [Help 1]

```
And this is after using -e -X options:
```
[DEBUG] Classpath:
[DEBUG]     file:/C:/GIT/jjwt/target/test-classes/
[DEBUG]     file:/C:/GIT/jjwt/target/classes/
[DEBUG]     file:/C:/Users/predrags/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.7.0/jackson-databind-2.7.0.jar
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Coverage check failed. See messages above.
        at org.codehaus.mojo.cobertura.tasks.CheckTask.execute(CheckTask.java:110)
        at org.codehaus.mojo.cobertura.CoberturaCheckMojo.execute(CoberturaCheckMojo.java:81)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]

```
This is the output for mvn -v:
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: C:\Program Files (x86)\Apache Software Foundation\apache-maven-3.3.9
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_60\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

```
I still ran `mvn dependency:copy-dependencies -DincludeScope=runtime` after the above error and this one finished successfully...

So, if the above error is not important, these are the JAR files, then:
```
jjwt-0.7.0-SNAPSHOT.jar
bcprov-jdk15on-1.51.jar
jackson-annotations-2.7.0.jar
jackson-core-2.7.0.jar
jackson-databind-2.7.0.jar
```

Does this look correct?

**Comment by lhazlewood** [comment]
The above error is not important.  Those jar files look correct.

**Comment by lhazlewood** [comment]
oh - you are using a SNAPSHOT build.  This is a volatile/changing build and is not guaranteed to work at all times.  You might want to checkout the latest git release tag to ensure a stable build.

**Comment by cope** [comment]
I used `git clone --branch 0.6.0 https://github.com/jwtk/jjwt.git` and it worked. Thanks :)
