### ISSUE TITLE
Unexpected SignatureException when parsing

### ISSUE THREAD

**Issue by cuyahoga** [jwtk/jjwt#210]
An access token is generated by a call to the Stormpath Client API, the signature is verified when I check it at https://www.jsonwebtoken.io/ using an API key secret from my Stormpath account, however when I parse it with jwkt 0.7.0 (using that same secret) I get a SignatureException thrown.

The access_token from Stormpath:
`eyJraWQiOiI1ODdXVjlaSlk0UFVCUk1BTkxCQzhYMlVCIiwic3R0IjoiYWNjZXNzIiwiYWxnIjoiSFMyNTYifQ.eyJqdGkiOiI0SHU2aFl0T0ZMMGNKcGZTZDJoaTZMIiwiaWF0IjoxNDg3MzI4NDgwLCJpc3MiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy83ZElsaXpCMnJCeG84YmpmQ3I1MDk5Iiwic3ViIjoiaHR0cHM6Ly9hcGkuc3Rvcm1wYXRoLmNvbS92MS9hY2NvdW50cy81TEJtb0VQbTdUREcxajhnRGxtcTZCIiwiZXhwIjoxNDg3MzUwMDgwLCJydGkiOiI0SHU2aFZaSktraGRoMFpiUW1xUlVIIn0.xMdKhezZcDuDNxPWfgYgFnq3bAXV90eY5gKZSmhpmuk`

The API key secret (don't worry - it's a demo disposable one):
`PUC2QKluk56M9g0YrX3ytiDATZO93lxjwpQ6BXI5IoI`

https://www.jsonwebtoken.io/ gives me the following code to use:
```
try {
    Jwts.parser()
	.setSigningKey("PUC2QKluk56M9g0YrX3ytiDATZO93lxjwpQ6BXI5IoI".getBytes("UTF-8"))
	.parseClaimsJws("eyJraWQiOiI1ODdXVjlaSlk0UFVCUk1BTkxCQzhYMlVCIiwic3R0IjoiYWNjZXNzIiwiYWxnIjoiSFMyNTYifQ.eyJqdGkiOiI0SHU2aFl0T0ZMMGNKcGZTZDJoaTZMIiwiaWF0IjoxNDg3MzI4NDgwLCJpc3MiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy83ZElsaXpCMnJCeG84YmpmQ3I1MDk5Iiwic3ViIjoiaHR0cHM6Ly9hcGkuc3Rvcm1wYXRoLmNvbS92MS9hY2NvdW50cy81TEJtb0VQbTdUREcxajhnRGxtcTZCIiwiZXhwIjoxNDg3MzUwMDgwLCJydGkiOiI0SHU2aFZaSktraGRoMFpiUW1xUlVIIn0.xMdKhezZcDuDNxPWfgYgFnq3bAXV90eY5gKZSmhpmuk");
    //OK, we can trust this JWT
} catch (SignatureException e) {
    //don't trust the JWT!
}
```

Which throws the following:
`io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:354)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:481)
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541)
	at uk.co.frontierag.testers.JwtDecode.jsonwebtokenExample(JwtDecode.java:53)
	at uk.co.frontierag.testers.JwtDecode.main(JwtDecode.java:43)`

**Comment by cuyahoga** [comment]
Ignore me, turns out I was using the wrong secret! I blame a two-fold problem with https://www.jsonwebtoken.io/

a) It incorrectly showed the signature as verified, even though it turned out I was using the **wrong** signature, so I put too much faith in it
b) It didn't render the "kid" element in the header, so I didn't realise I was feeding the secret from a different pair in the Java code, which is why it was failing to validate

When I popped the access token into https://jwt.io/, it rendered the header correctly, I immediately saw it was a different "kid" and supplying the corresponding secret to the Jwts parser in code worked as expected. More coffee needed ...
