### ISSUE TITLE
Fails with Java 9

### ISSUE THREAD

**Issue by halber** [jwtk/jjwt#259]
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26)
	at io.jsonwebtoken.impl.DefaultJwtParser.setSigningKey(DefaultJwtParser.java:151)
	at com.xonnec.testauth0jwt.App.main(App.java:53)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 3 more

**Comment by aspecialkey** [comment]
0.9.0

`java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.jsonwebtoken.impl.Base64Codec.encode(Base64Codec.java:21)
	at io.jsonwebtoken.impl.Base64UrlCodec.encode(Base64UrlCodec.java:22)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.base64UrlEncode(DefaultJwtBuilder.java:349)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.compact(DefaultJwtBuilder.java:295)
`

**Comment by dogeared** [comment]
Please provide more information. Here's my output:

```
[micahsilverman:~/Projects/jjwt] master:* ± jenv local 9.0
[micahsilverman:~/Projects/jjwt] master:* ± java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
[micahsilverman:~/Projects/jjwt] master:* ± mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JSON Web Token support for the JVM 0.10.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.561 s
[INFO] Finished at: 2017-11-08T16:55:20-05:00
[INFO] Final Memory: 68M/227M
[INFO] ------------------------------------------------------------------------
```

**Comment by TheMarcoD** [comment]
This issue still persists. I tested it with Java 11 and version 0.9.1 of io.jsonwebtoken.

The error message is `java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter`.

The error also only happens when you run the application. The external dependencies are resolved at class initialization time.

The solution for me was to import an outdated version of JAX-B in Maven:
```
<dependency>
  <groupId>javax.xml.bind</groupId>
  <artifactId>jaxb-api</artifactId>
  <version>2.3.1</version>
</dependency>
```

This dependency has long been replaced by:
```
<!-- https://mvnrepository.com/artifact/jakarta.xml.bind/jakarta.xml.bind-api -->
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>3.0.1</version>
</dependency>
```
But this won't work because the class path is different.

**Comment by lhazlewood** [comment]
@TheMarcoD You're referencing a version that is 3 1/2 years old (`0.9.1`), and many fixes have occurred since then.  Ensure you're using the latest stable release (`0.11.2` at the time of this message), using the correct [Maven dependency declarations](https://github.com/jwtk/jjwt#maven) (which are different than 0.9.x), and try again.

**Comment by TheMarcoD** [comment]
Thank you! I didn't realize that you split the dependencies and thought 0.9.1 is the latest build.

**Comment by lhazlewood** [comment]
@TheMarcoD Yep, the project documentation is always the source of truth - not what shows up in Maven Central with artifact names.
