### ISSUE TITLE
ObjectMapper cannot be resolved to a type

### ISSUE THREAD

**Issue by SoundJunkie** [jwtk/jjwt#303]
I just can't get beyond this:

Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The import com.fasterxml.jackson.databind cannot be resolved
	ObjectMapper cannot be resolved to a type
	ObjectMapper cannot be resolved to a type
	ObjectMapper cannot be resolved to a type

	at io.jsonwebtoken.impl.DefaultJwtBuilder.<init>(DefaultJwtBuilder.java:19)
	at io.jsonwebtoken.Jwts.builder(Jwts.java:116)
	at jwt.Test.main(Test.java:25)

I have the core, databind and annotation jars in the build path (just a raw java project in Eclipse, Java8).  Have 2.8.9 versions (and higher). I'm just trying to run your base example.

Any help would be appreciated.

**Comment by SoundJunkie** [comment]
I download lasted jjwt jar and the problem went away.
