### ISSUE TITLE
jjwt cant parse token generated from different service

### ISSUE THREAD

**Issue by sattlerio** [jwtk/jjwt#315]
Hi,

I generate my JWT in a different service --> Python with Flask JWT Extended.
My Secret Key  is "secret".
Thats how I generate in my service the JWT:
```

identity = {
        "firstname": user.firstname,
        "lastname": user.lastname,
        "email": user.email,
        "uuid": user.user_uuid,
        'user_id': user.id
    }
    access_token = create_access_token(identity=identity, fresh=True)
```

In my Java Service I try to decode the JWT:

`Jwts.parser().setSigningKey("secret").parseClaimsJws(token);`

But I get always this exception:
```

2018-03-26 11:12:12.188 ERROR [gateway-server,1913cbe663580b57,1913cbe663580b57,false] 17026 --- [nio-8080-exec-1] c.s.m.api_gateway.filters.pre.PreFilter  : JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.

io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:354) ~[jjwt-0.9.0.jar!/:0.9.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:481) ~[jjwt-0.9.0.jar!/:0.9.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541) ~[jjwt-0.9.0.jar!/:0.9.0]

```

If I use any online token decoder like jwt.io or anything else I can decode it succesfully

Thanks

**Comment by azagniotov** [comment]
@sattlerio I am just curious, since you mentioned you can decode the token successfully

The `jwt.io` successfully decodes a token since it is base64 encoded. But, it does not verify the signature by default. To verify signature using the `jwt.io` you need to paste there your keys. 

So, are you just decoding or actually verifying the signature using `jwt.io`?

**Comment by arracso** [comment]
@azagniotov Hi, I'm having same issue, I can't **verify** tokens generated by jjwt on jwt.io. 
For me is just fine, because I won't pass the token to any other application. But, I think the authors may want to fix this. 

- **algorithm**: HS256
- **graddle**: `compile 'io.jsonwebtoken:jjwt:0.9.0'`

**Comment by azagniotov** [comment]
Are you saying that you cannot decode the base64 encoded JWT on jwt.io?

**Comment by arracso** [comment]
no, I can decode the JWT but I can't verify it using jwt.io (jwt.io also have this functionality)

**Comment by lhazlewood** [comment]
jwt.io allows for insecure keys, and they shouldn't.

Read the JavaDoc on `setSigningKey` - the string argument must be Base64, not a plaintext password.  If it's not Base64, you're likely using an insecure key. (`secret` is definitely an insecure key).  Here's why:

https://stackoverflow.com/questions/40252903/static-secret-as-byte-key-or-string/40274325#40274325

Once you've generated a secure key, choose the 'base64' checkbox on jwt.io.

Based on this, is there work for the JJWT team to accomplish?  If not, we should close this issue.  In general, non-actionable work or questions should be posted on StackOverflow using the `#jjwt` tag. Thanks!

**Comment by lhazlewood** [comment]
Closing due to inactivity.  Additionally `jwt.io` has been known to be buggy and allows insecure keys, so it is not a valid litmus test for a JWT parser.

If you believe there is actionable work to modify the JJWT code, please open a new issue explaining the problem.  Thanks!
