### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method toList()

### ISSUE THREAD

**Issue by jurajjurci** [jwtk/jjwt#380]
Hi,
my usage of the newest version of your library throws exception

`java.lang.NoSuchMethodError: No virtual method toList()Ljava/util/List; in class Lorg/json/JSONArray; or its super classes (declaration of 'org.json.JSONArray' appears in /system/framework/core-libart.jar)
        at io.jsonwebtoken.io.OrgJsonDeserializer.toList(OrgJsonDeserializer.java:71)
        at io.jsonwebtoken.io.OrgJsonDeserializer.convertIfNecessary(OrgJsonDeserializer.java:83)
        at io.jsonwebtoken.io.OrgJsonDeserializer.toMap(OrgJsonDeserializer.java:63)
        at io.jsonwebtoken.io.OrgJsonDeserializer.convertIfNecessary(OrgJsonDeserializer.java:85)
        at io.jsonwebtoken.io.OrgJsonDeserializer.toMap(OrgJsonDeserializer.java:63)
        at io.jsonwebtoken.io.OrgJsonDeserializer.parse(OrgJsonDeserializer.java:48)
        at io.jsonwebtoken.io.OrgJsonDeserializer.deserialize(OrgJsonDeserializer.java:32)
        at io.jsonwebtoken.impl.DefaultJwtParser.readValue(DefaultJwtParser.java:585)
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:301)
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:513)
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:573)`

**Comment by jurajjurci** [comment]
Thank you, it works now.
