### ISSUE TITLE
[JWT][JJWT] Function compact() very slow

### ISSUE THREAD

**Issue by V1HVN** [jwtk/jjwt#396]
I use lib JJWT 0.9.0 to generate Token. I have write log code segment generate Token, and I see function compact() run verry slow (664 -151 = 513(ms)) . I used JDK 7. how to the function compact() run faster or How to generate tokens faster? My code:

```
public String createJWT(String id, String issuer, String subject, List<T> authories, String loginUserData,
            long ttlMillis) {
        //The JWT signature algorithm we will be using to sign the token
        long startTime = System.currentTimeMillis();
        LOGGER.info("createJWT id=" + id + ";issuer=" + ";subject=" + subject);
        SignatureAlgorithm signatureAlgorithm = SignatureAlgorithm.HS512;

        long nowMillis = System.currentTimeMillis();
        Date now = new Date(nowMillis);

        //We will sign our JWT with our ApiKey secret
        byte[] apiKeySecretBytes = DatatypeConverter.parseBase64Binary(ApiSecretKey.getSecretKey());
        Key signingKey = new SecretKeySpec(apiKeySecretBytes, signatureAlgorithm.getJcaName());

        //Let's set the JWT Claims
        JwtBuilder builder = Jwts.builder().setId(id).setIssuedAt(now).setSubject(subject)
                .setIssuer(issuer);
        if (!CheckObjectUtils.isNullOrEmpty(authories)) {
            builder.claim(AUTHORITIES_KEY, authories);
        }
        if (!CheckObjectUtils.isNullOrEmpty(loginUserData)) {
            builder.claim(LOGIN_USER_DATA_KEY, loginUserData);
        }

        builder.signWith(signatureAlgorithm, signingKey);

        //if it has been specified, let's add the expiration
        if (ttlMillis >= 0) {
            long expMillis = nowMillis + ttlMillis;
            Date exp = new Date(expMillis);
            builder.setExpiration(exp);
        }
        LOGGER.info("createJWT process id=" + id + ";issuer=" + ";subject=" + subject + ";time(ms)="
                + (System.currentTimeMillis() - startTime));
        //Builds the JWT and serializes it to a compact, URL-safe string        
        String token = builder.compact();
        LOGGER.info("createJWT end id=" + id + ";issuer=" + ";subject=" + subject + ";time(ms)="
                + (System.currentTimeMillis() - startTime));
        return token;
    }

JsonWebTokenRestApi<Long> jwtApi = new JsonWebTokenRestApiFactory(
                JsonWebTokenRestApiFactory.JWT_JJWT).getJsonWebTokenByType();
        String jwt = jwtApi.createJWT(null, null, "vinhhc_vsc", null, null, 18000);
```

My console log:
```

createJWT id=null;issuer=;subject=vinhhc_vsc
createJWT process id=null;issuer=;subject=vinhhc_vsc;time(ms)=151
createJWT end id=null;issuer=;subject=vinhhc_vsc;time(ms)=664
```

Thanks!

**Comment by lhazlewood** [comment]
Please use the latest stable release (0.10.5 at the time of this comment) and run your test again.

Also, do you have a standalone code snippet that I can run to re-create your test locally?  Without this, there is no way to perform objective performance comparisons.

**Comment by V1HVN** [comment]
I'll try and answer you soon.
Thank!

**Comment by V1HVN** [comment]
I'll try and answer you soon.
Thank!

**Comment by V1HVN** [comment]
I'll try it(jjwt-api-0.10.5.jar), but it's failed. 
This is error detail:

io.jsonwebtoken.lang.UnknownClassException: Unable to load class named [io.jsonwebtoken.impl.DefaultJwtBuilder] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.
	at io.jsonwebtoken.lang.Classes.forName(Classes.java:92)
	at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:136)
	at io.jsonwebtoken.Jwts.builder(Jwts.java:115)

Please help me!

**Comment by dfavaro** [comment]
> I'll try it(jjwt-api-0.10.5.jar), but it's failed.
> This is error detail:
> 
> io.jsonwebtoken.lang.UnknownClassException: Unable to load class named [io.jsonwebtoken.impl.DefaultJwtBuilder] from the thread context, current, or system/application ClassLoaders. All heuristics have been exhausted. Class could not be found.
> at io.jsonwebtoken.lang.Classes.forName(Classes.java:92)
> at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:136)
> at io.jsonwebtoken.Jwts.builder(Jwts.java:115)
> 
> Please help me!

same here

**Comment by lhazlewood** [comment]
What does your maven or gradle configuration look like?  Did you follow the [Installation instructions](https://github.com/jwtk/jjwt#install) ?

Please do not change the focus of this ticket which is specifically about `compact()` performance.  If you have general purpose questions about JJWT and you don't know if it is actually a bug, please ask them on StackOverflow.com and use the `jjwt` tag.  Thanks!

**Comment by pierre-laurens** [comment]
Hello. I have the same problem. I'm using the latest jjwt (0.9.0 version).  what I can say is that the problem occurs the first time the compact method is called in the JVM.
Sample code
`	private static void testForGit(){
		int cpt = 0;
		while (cpt < 10){
			long nowMillis = System.currentTimeMillis();
			Date now = new Date(nowMillis);
			JwtBuilder builder = Jwts.builder()
	                .setIssuedAt(now)
	                .signWith(SignatureAlgorithm.HS256, "azertyuiop".getBytes());


			long expMillis = nowMillis + 2000;
			Date exp = new Date(expMillis);
			//builder.setExpiration(exp);
	
			//Builds the JWT and serializes it to a compact, URL-safe string
			long begin = System.currentTimeMillis();
			builder.compact();
			System.out.println("elapsed time =" + (System.currentTimeMillis() - begin));
			cpt++;
		}
	}`

Result in console log : 
`elapsed time =203
elapsed time =1
elapsed time =0
elapsed time =0
elapsed time =0
elapsed time =0
elapsed time =0
elapsed time =1
elapsed time =0
elapsed time =0
`
thanks

**Comment by lhazlewood** [comment]
@pierre-laurens 0.9.0 is not the latest version.  0.10.5 is.  HTH!

**Comment by lhazlewood** [comment]
Also, a slow initial run is nothing unusual.  The additional runs are the JVM performing JIT optimizations.  This is normal/expected for most Java code, not just JJWT.

**Comment by kishoretangudu** [comment]
Hi I am following the documentation to create JWT token. I am using jjwt 0.10.5 version. This is the only entry I have in my pom.xml. I am seeing this issue. Please help me.

=================
io.jsonwebtoken.lang.UnknownClassException: Unable to load class named [io.jsonwebtoken.impl.DefaultJwtBuilder] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.
	at io.jsonwebtoken.lang.Classes.forName(Classes.java:92) ~[jjwt-api-0.10.5.jar:na]
	at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:136) ~[jjwt-api-0.10.5.jar:na]
	at io.jsonwebtoken.Jwts.builder(Jwts.java:115) ~[jjwt-api-0.10.5.jar:na]
	at com.jci.spring.practice.service.PracticeService.createJWT(PracticeService.java:31) ~[classes/:na]
	at com.jci.spring.practice.PracticeController.login(PracticeController.java:29) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) ~[spring-webmvc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) ~[spring-webmvc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877) ~[spring-webmvc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

fddff
dg
2019-01-02 22:10:37.637 ERROR 12676 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.jsonwebtoken.lang.UnknownClassException: Unable to load class named [io.jsonwebtoken.impl.DefaultJwtBuilder] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.] with root cause

**Comment by kishoretangudu** [comment]
@lhazlewood Please respond the above issue ASAP. Anticipating quick reply. Thank you.

**Comment by lhazlewood** [comment]
@kishoretangudu please ask usability questions on StackOverflow using the `#jjwt` tag.  GitHub Issues is only used to track actionable work to change the JJWT codebase.

**Comment by SharkFourSix** [comment]
There's clearly a problem with this if a lot of people are having this problem. And verbatim installation procedures are what I used in my case. Still, I still get the same errors. The classes are not bundled in the final jar file for some reason.
