### ISSUE TITLE
Unsupported Class Version Error(io/jsonwebtoken/Jwts) while using in jboss eap 6 with ibm jdk1.6

### ISSUE THREAD

**Issue by javatechbytes** [jwtk/jjwt#403]
Hi,

We are using below jwtk version in our project deployed in jboss eap 6.0 and ibm jdk 1.6 version.
 <dependency>
          <groupId>io.jsonwebtoken</groupId>
          <artifactId>jjwt-api</artifactId>
          <version>0.10.5</version>
      </dependency>
While running the application we are getting below exception. Could you please help me to resolve this ? Any work around without upgrading JDK ? If upgrade is required what is the JRE  version we have to upgrade?

LOG:
Service Module Loader: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=io/jsonwebtoken/Jwts, offset=6
	at java.lang.ClassLoader.defineClassImpl(Native Method) [vm.jar:1.6.0]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:287) [vm.jar:1.6.0]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:74) [security.jar:]
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:327) [jboss-modules-1.2.0.CR1.jar:1.2.0.CR1]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:391) [jboss-modules-1.2.0.CR1.jar:1.2.0.CR1]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoade

Thanks in Advance,
Grani

**Comment by lhazlewood** [comment]
JJWT 0.x supports JDK 1.7 and later.  1.6 is not supported and there are no plans to support it.

JJWT 1.0 final will only support 1.8 and later.

Cheers!
