### ISSUE TITLE
Keys.keyPairFor(SignatureAlgorithm.<whatever>) throws Method threw 'java.lang.NoSuchMethodError' exception.

### ISSUE THREAD

**Issue by sscarduzio** [jwtk/jjwt#411]
I'm trying to generate a key pair on the fly in my tests:
```java
// Both throw the same exception
Keys.keyPairFor(SignatureAlgorithm.ES256)
Keys.keyPairFor(SignatureAlgorithm.RS512)
```

And I get this exception:
```java
java.lang.NoSuchMethodError: io.jsonwebtoken.lang.Classes.invokeStatic(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Class;[Ljava/lang/Object;)Ljava/lang/Object;

	at io.jsonwebtoken.security.Keys.keyPairFor(Keys.java:210)
	at tech.beshu.ror.acl.blocks.rules.impl.JwtAuthRuleTests.shouldAcceptTokenWithValidEllipticCurveSignature(JwtAuthRuleTests.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
I'm using the latest version:

```
  compile 'io.jsonwebtoken:jjwt-api:0.10.5'
    runtime 'io.jsonwebtoken:jjwt-impl:0.10.5',
            // Uncomment the next line if you want to use RSASSA-PSS (PS256, PS384, PS512) algorithms:
            'org.bouncycastle:bcprov-jdk15on:1.60',
            'io.jsonwebtoken:jjwt-jackson:0.10.5'

```
Not sure what I'm doing wrong, as this should work as per documentation, right?

**Comment by lhazlewood** [comment]
@sscarduzio it shouldn't be, but it sounds like something is incorrect with the dependency declarations in your project between test and non-test code.  Could you please verify?  I'd like to close this issue if so.

**Comment by lhazlewood** [comment]
Closing due to inactivity.  Please let me know if this is still an issue and we can discuss re-opening.

**Comment by Wouter8** [comment]
I get the same error when running normally. I'm running it through Payara 5. Had to add the .jar files to the Payara installation but now I'm getting this error. Any help would be appreciated

**Comment by marcoderama** [comment]
I'm not sure if this explains the original issue but this might help others that ended up here for the same/similar problem as @Wouter8.

My package was configured to use jjwt-api 0.10.7.  Unit tests ran fine but when the package was used in a larger project, I ran into the same issue with `io.jsonwebtoken.lang.Classes.invokeStatic`.   After many frustrating hours we figured out that the problem was due to some other package bringing in `jjwt-0.6.0`.  Both `jjwt-api-0.10.x` and `jjwt-0.6.0` implement `io.jsonwebtoken.lang.Classes` but the latter doesn't have the `Classes.invokeStatic` method.  If `jjwt-0.6.0` ends up earlier in your classpath, then its definitions shadow the ones in `jjwt-api-0.10.x` and you get the `NoSuchMethod` error.

Our tools (sbt) didn't flag the conflict because it couldn't know that `jjwt` and `jjwt-api` were "the same thing".

**Comment by Scarysize** [comment]
@marcoderama Thanks for sharing! We actually have the same issue. We upgraded from 0.9.x to 0.11.x and also had conflicting versions without `sbt` noticing anything. Really frustrating...

For searchability, our exception was with the `signWith` method:

```sh
Exception in thread "main" java.lang.NoSuchMethodError: io.jsonwebtoken.JwtBuilder.signWith(Ljava/security/Key;Lio/jsonwebtoken/SignatureAlgorithm;)Lio/jsonwebtoken/JwtBuilder;
```

**Comment by ChocolateOverflow** [comment]
What are the current latest compatible versions of the dependencies relating to this issue? I'm using `jjwt-0.9,1` and I've tried `jjwt-api-0.10-x` with no luck.

**Comment by bdemers** [comment]
Hi! @ChocolateOverflow take a look at: https://github.com/jwtk/jjwt#installation for examples (and the current version)

**Comment by ChocolateOverflow** [comment]
I've figured out that I needed to remove the `jjwt` dependency and have just the 3 listed in `#installation`.
