### ISSUE TITLE
Adding jjwt as a dependency causes NoClassDefFoundError

### ISSUE THREAD

**Issue by dsmclaughlin** [jwtk/jjwt#412]
Hi,

I've been googling around for a while, and looked at related issues here, but can't find a solution to my problem. I hope someone here can help :)

I have an application that runs an embedded jetty server, I'm trying to add JWT support to this application. The new code I have written to support JWT compiles fine but when I make any request to the server I get an Exception with the following stack trace, even before my JWT handling code is called.

If I revert the jjwt dependencies from my pom, my application behaves as normal.

The error:

> [WARN ] 2018-11-20 23:16:57.281 [qtp992768706-16] HttpChannel - /api/auth/login
> javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge
> 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489) ~[jersey-container-servlet-core-2.23.2.jar:?]
> 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) ~[jersey-container-servlet-core-2.23.2.jar:?]
> 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) ~[jersey-container-servlet-core-2.23.2.jar:?]
> 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) ~[jersey-container-servlet-core-2.23.2.jar:?]
> 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) ~[jersey-container-servlet-core-2.23.2.jar:?]
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) ~[jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) ~[jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]

(there is more, omitted for brevity)

I'm running Java 8, my jetty version is currently 9.4.7.v20170914 and the appropriate jersey dependencies to list are (i think)

> 		<dependency>
> 			<groupId>org.glassfish.jersey.containers</groupId>
> 			<artifactId>jersey-container-servlet</artifactId>
> 			<version>2.23.2</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.glassfish.jersey.media</groupId>
> 			<artifactId>jersey-media-json-jackson</artifactId>
> 			<version>2.9</version>
> 		</dependency>

I'm reasonably sure this is some sort of dependency conflict, but I'm not sure how to solve it. If anyone can give any direction on how to resolve it I would be very grateful. Many thanks in advance!

**Comment by dsmclaughlin** [comment]
I found a solution to this. I upgraded the following dependencies:

> 		<dependency>
> 			<groupId>org.glassfish.jersey.containers</groupId>
> 			<artifactId>jersey-container-servlet</artifactId>
> 			<version>2.23.2</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.glassfish.jersey.media</groupId>
> 			<artifactId>jersey-media-json-jackson</artifactId>
> 			<version>2.9</version>
> 		</dependency>

as well as adding a new dependency:

> 		<dependency>
> 			<groupId>org.glassfish.jersey.containers</groupId>
> 			<artifactId>jersey-container-servlet</artifactId>
> 			<version>2.27</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.glassfish.jersey.media</groupId>
> 			<artifactId>jersey-media-json-jackson</artifactId>
> 			<version>2.27</version>
> 		</dependency>
>                 <dependency>
>                          <groupId>org.glassfish.jersey.inject</groupId>
>                          <artifactId>jersey-hk2</artifactId>
>                          <version>2.27</version>
>                  </dependency>
