### ISSUE TITLE
Problem on Android with release build

### ISSUE THREAD

**Issue by Trancever** [jwtk/jjwt#433]
Hello :)

First of all thanks for this lib, it's really helpful. 
However, we have a problem on a release build.

That is stackTrace of the error we get and it only happens on release build:
```
02-07 09:58:02.527 13097 13136 W System.err: io.a.a.c: Unable to load class named [io.jsonwebtoken.impl.DefaultJwtParser] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.
02-07 09:58:02.527 13097 13136 W System.err: 	at io.a.a.a.a(Unknown Source:105)
02-07 09:58:02.527 13097 13136 W System.err: 	at io.a.a.a.b(Unknown Source:0)
02-07 09:58:02.527 13097 13136 W System.err: 	at io.a.i.a(Unknown Source:7)
02-07 09:58:02.527 13097 13136 W System.err: 	at com.reactnative.crypto.CryptoModule.decodeJwt(Unknown Source:96)
02-07 09:58:02.527 13097 13136 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 09:58:02.527 13097 13136 W System.err: 	at com.facebook.react.bridge.v.a(Unknown Source:190)
02-07 09:58:02.528 13097 13136 W System.err: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:23)
02-07 09:58:02.528 13097 13136 W System.err: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
02-07 09:58:02.528 13097 13136 W System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
02-07 09:58:02.528 13097 13136 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-07 09:58:02.528 13097 13136 W System.err: 	at com.facebook.react.bridge.queue.a.dispatchMessage(Unknown Source:0)
02-07 09:58:02.528 13097 13136 W System.err: 	at android.os.Looper.loop(Looper.java:164)
02-07 09:58:02.528 13097 13136 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(Unknown Source:16)
02-07 09:58:02.528 13097 13136 W System.err: 	at java.lang.Thread.run(Thread.java:764)
```

Our configuration in build.gradle:
```
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dependencies {
        api 'io.jsonwebtoken:jjwt-api:0.10.5'
        runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.10.5' 
        runtimeOnly('io.jsonwebtoken:jjwt-orgjson:0.10.5') {
            exclude group: 'org.json', module: 'json' //provided by Android natively
        }
    }
```

and proguard-rules.pro:
```
# jjwt-api
-keepattributes InnerClasses

-keep class io.jsonwebtoken.** { *; }
-keepnames class io.jsonwebtoken.* { *; }
-keepnames interface io.jsonwebtoken.* { *; }
```

What is also important is fact that I showed here config of "our" library that uses this library. Then we consume "our" library in Android app.

Do you see anything wrong in the configuration?

**Comment by Trancever** [comment]
It was issue with proguard configuration. Had to put proper pro guard rules into app proguard-rules file instead of library.
