### ISSUE TITLE
 io.jsonwebtoken.impl.compression.DeflateCompressionCodec not a subtype

### ISSUE THREAD

**Issue by Nijacvk** [jwtk/jjwt#570]
Hi,

I got an error message:  io.jsonwebtoken.impl.compression.DeflateCompressionCodec not a subtype when checking a jwt. Can somebody tell me what is causing the problem an dhow toi fix it?

**Comment by Nijacvk** [comment]
Caused by: java.util.ServiceConfigurationError: io.jsonwebtoken.CompressionCodec: Provider io.jsonwebtoken.impl.compression.DeflateCompressionCodec not a subtype
	at java.util.ServiceLoader.fail(Unknown Source)
	at java.util.ServiceLoader.access$300(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
	at java.util.ServiceLoader$1.next(Unknown Source)
	at io.jsonwebtoken.impl.lang.Services.loadAll(Services.java:47)
	at io.jsonwebtoken.impl.compression.DefaultCompressionCodecResolver.<init>(DefaultCompressionCodecResolver.java:60)
	at io.jsonwebtoken.impl.DefaultJwtParserBuilder.<init>(DefaultJwtParserBuilder.java:48)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:156)
	at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:136)
	at io.jsonwebtoken.Jwts.parserBuilder(Jwts.java:130)

**Comment by lhazlewood** [comment]
Unfortunately, that's not enough information to find the problem.  Please provide a test case.

**Comment by lhazlewood** [comment]
Unable to reproduce, and no follow-up from OP.  Please feel free to comment if you have a test case that can re-produce this issue and I'll be happy to re-open it.

(Also, please ensure you're using the latest stable release of 0.11.0).

**Comment by Nijacvk** [comment]
Hi Les,

Thanks for your response.

I’ve used the latest release and it happens only when the methode is called a number of times.

I’ll try to create a test case.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Les Hazlewood <notifications@github.com>
Verzonden: Wednesday, March 11, 2020 6:13:36 PM
Aan: jwtk/jjwt <jjwt@noreply.github.com>
CC: Nijacvk <nijac@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [jwtk/jjwt] io.jsonwebtoken.impl.compression.DeflateCompressionCodec not a subtype (#570)


Unable to reproduce, and no follow-up from OP. Please feel free to comment if you have a test case that can re-produce this issue and I'll be happy to re-open it.

(Also, please ensure you're using the latest stable release of 0.11.0).
