### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: qTESLA

### ISSUE THREAD

**Issue by hyperxpro** [jwtk/jjwt#596]
Error while generating JWT.

Exception:
```java
Exception in thread "main" java.lang.NoSuchFieldError: qTESLA
	at org.bouncycastle.pqc.asn1.PQCObjectIdentifiers.<clinit>(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadPQCKeys(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.setup(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.access$000(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:156)
	at io.jsonwebtoken.lang.RuntimeEnvironment.enableBouncyCastleIfPossible(RuntimeEnvironment.java:53)
	at io.jsonwebtoken.lang.RuntimeEnvironment.<clinit>(RuntimeEnvironment.java:62)
	at io.jsonwebtoken.impl.crypto.RsaProvider.<clinit>(RsaProvider.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.jsonwebtoken.lang.Classes.invokeStatic(Classes.java:198)
	at io.jsonwebtoken.security.Keys.keyPairFor(Keys.java:221)
	at MyClass.main(MyClass.java:19)
```

Code:
```java
KeyPair keyPair = Keys.keyPairFor(SignatureAlgorithm.RS256);
String jws = Jwts.builder().setSubject("Joe").signWith(keyPair.getPrivate()).compact();
Jwts.parserBuilder()
                .setSigningKey(keyPair.getPublic())
                .build()
                .parseClaimsJws(jws);
```

**Comment by lhazlewood** [comment]
I just ran this test locally and it passed, using the following dependency:

```xml
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
    <version>1.60</version>
    <scope>test</scope>
</dependency>
```

What version of the JDK are you using? And version of BouncyCastle?

Do you have a quick test project in GitHub we can clone to test?

**Comment by hyperxpro** [comment]
Solved!

The problem was, a dependency was importing an old version of BouncyCastle which caused conflict with the new version. I excluded old version manually from `pom.xml` and everything works fine with new version of BouncyCastle.
