### ISSUE TITLE
io.jsonwebtoken.CompressionCodec: Error reading configuration file

### ISSUE THREAD

**Issue by zhangwenhua-tron** [jwtk/jjwt#648]
Hi,
I found an error message when I use jjwt, how does this error happen?
It seems that it is not an exception, so I cannot catch it.

**Comment by lhazlewood** [comment]
No code example? Test case? Sample application?  It's impossible for us to help without more information.

Also, for future usability questions, please kindly read https://github.com/jwtk/jjwt#help-questions before opening a GitHub issue.  Thanks!

**Comment by zhangwenhua-tron** [comment]
I know it is a weird question， after I reboot my application, there is no more errors.
I cannot reproduce it, but I don't know why it occurred...

**Comment by mrwilby** [comment]
@lhazlewood we're seeing the same in our AWS API Gateway+Lambda logs. This happens sporadically, and since AWS is recycling the underlying lambda container instances behind the scenes it's very difficult for us to create a reproducer for this. 

Our guess is that something is leaking file/stream/IO handles (at least the call stack would appear to suggest as much). It might be a good idea to carefully review the stream-handling and make sure all resources are correctly being closed/released

Here's an exert from one of our logs:

```
5686535 [main] WARN  com.company.flows.AccessTokenFlow - Rejecting request due to exception 
java.util.ServiceConfigurationError: io.jsonwebtoken.CompressionCodec: Error reading configuration file
at java.util.ServiceLoader.fail(ServiceLoader.java:232)
at java.util.ServiceLoader.parse(ServiceLoader.java:309)
at java.util.ServiceLoader.access$200(ServiceLoader.java:185)
at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
at io.jsonwebtoken.impl.lang.Services.loadAll(Services.java:80)
at io.jsonwebtoken.impl.lang.Services.loadAll(Services.java:68)
at io.jsonwebtoken.impl.compression.DefaultCompressionCodecResolver.<init>(DefaultCompressionCodecResolver.java:60)
at io.jsonwebtoken.impl.DefaultJwtParser.<init>(DefaultJwtParser.java:72)
at sun.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at java.lang.Class.newInstance(Class.java:442)
at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:156)
at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:136)
at io.jsonwebtoken.Jwts.parser(Jwts.java:121)
at com.company.core.security.token.jwt.JsonWebTokenParser.<init>(JsonWebTokenParser.java:48)
at com.company.core.security.token.jwt.JsonWebTokenFactory.parser(JsonWebTokenFactory.java:10)
at com.company.core.security.authorization.framework.bridge.AuthorizationBridge.extractAccessTokenExpiration(AuthorizationBridge.java:429)
at com.company.core.security.authorization.framework.bridge.AuthorizationBridge.serializeData(AuthorizationBridge.java:78)
at com.company.security.authz.apigateway.flows.AccessTokenFlow.handleRequest(AccessTokenFlow.java:76)
at com.company.security.authz.apigateway.flows.DefaultCustomAuthorizerFlowManager.handleRequest(DefaultCustomAuthorizerFlowManager.java:46)
at com.company.security.authz.apigateway.CustomAuthorizer.handleRequest(CustomAuthorizer.java:57)
at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:263)
at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:180)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:903)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:349)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:70)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150)
Caused by: java.io.FileNotFoundException: /var/task/META-INF/services/io.jsonwebtoken.CompressionCodec ()
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at java.io.FileInputStream.<init>(FileInputStream.java:93)
at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
at java.net.URL.openStream(URL.java:1093)
at java.util.ServiceLoader.parse(ServiceLoader.java:304)
... 33 common frames omitted
5686536 [main] WARN  com.company.a.e.ApiGatewayException - Request rejected due to Unauthorized: Exception during request processing 
Unauthorized: com.company.security.authz.aws.apigateway.exceptions.ApiGatewayException
com.company.security.authz.aws.apigateway.exceptions.ApiGatewayException: Unauthorized
	at com.company.security.authz.aws.apigateway.exceptions.ApiGatewayException.newUnauthorized(ApiGatewayException.java:20)
	at com.company.security.authz.apigateway.flows.AccessTokenFlow.handleRequest(AccessTokenFlow.java:84)
	at com.company.security.authz.apigateway.flows.DefaultCustomAuthorizerFlowManager.handleRequest(DefaultCustomAuthorizerFlowManager.java:46)
	at com.company.security.authz.apigateway.CustomAuthorizer.handleRequest(CustomAuthorizer.java:57)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

END RequestId: c1c9a7f8-225f-42df-83f6-2716e310a045
REPORT RequestId: c1c9a7f8-225f-42df-83f6-2716e310a045	Duration: 106.60 ms	Billed Duration: 107 ms	Memory Size: 3008 MB	Max Memory Used: 677 MB	
```

Is it possible to reopen this ticket?

**Comment by lhazlewood** [comment]
@mrwilby - thanks for the stack trace, that was helpful!

It's so weird that you posted this today - another problem with `ServiceLoader` was discussed today: #751 

This is due to the way JJWT uses the JDK `ServiceLoader` to look up pluggable implementations:  `ServiceLoader` looks for a file in `META-INF` that contains a fully qualified class name of the implementation class to instantiate.  The "too many open files" message in the stack trace sounds like Lambda's file I/O is having problems when accessing that file within the dependency .jar.

So just like in #751, the workaround for this (until we can address the `ServiceLoader` calls) is to instantiate and configure a CompressionCodec instance directly on the `JwtBuilder` and/or` JwtParser (in your case, a `CompressionCodecResolver` that is used at parse time to return the corresponding `CompressionCodec` instance as documented here: https://github.com/jwtk/jjwt/tree/0.10.7#compression-custom).

The logic that calls `ServiceLoader` is only invoked if the respective component is not explicitly configured.  So if you explicitly configure an instance, `ServiceLoader` is never called.  Please see #751 and the discussion there.

I'll consider this issue a duplicate of that one, so I don't think it needs be re-opened, unless I'm missing something.

cc @bdemers

**Comment by mrwilby** [comment]
Thanks @lhazlewood . We're not actually using compression in our system, so we'll possibly disable that as you suggested.

However, I'm still not clear on what is actually responsible for the handle leak. Do you believe that the root cause of the problem is somehow related to the ServiceLoader calls themselves?

**Comment by lhazlewood** [comment]
@mrwilby it most definitely is.  The JDK `ServiceLoader` implementation will look for a file in any .jar's `META-INF/services/` directory for a file with the same name as the interface (e.g. `com.whatever.my.Interface`).  It will then read that file's first line to determine the fully qualified class name of the implementation of that interface.  It will finally create an instance of that implementation fqcn and return it.

This is corroborated by your stack trace's line:

> Caused by: java.io.FileNotFoundException: /var/task/META-INF/services/io.jsonwebtoken.CompressionCodec (Too many open files)

and more directly, it's the `ServiceLoader` implementation at the top of the stack:

```bash
at java.util.ServiceLoader.fail(ServiceLoader.java:232)
at java.util.ServiceLoader.parse(ServiceLoader.java:309)
at java.util.ServiceLoader.access$200(ServiceLoader.java:185)
at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
at io.jsonwebtoken.impl.lang.Services.loadAll(Services.java:80)
```

So as you can see, JJWT's `Services` class calls the JDK's `ServiceLoader` API, and then it fails from within there.  Since we didn't write that code, we can't do anything about it other than suggest the aforementioned workaround and/or change our implementation to not use the JDK `ServiceLoader` on a future release.

I hope that helps!

cc @bdemers

**Comment by lhazlewood** [comment]
Based on recent discussion here (thank you @mrwilby ! ), this issue has been superseded by #752.

**Comment by lyz-tech** [comment]
I also have this problem

**Comment by mrwilby** [comment]
We're using Open JDK 8 (I can check the specific version if it helps).
However, just to muddy the water a little, we did find a potential handle leak in our own code. This makes me wonder whether the leak is outside of the JJWT library and that it just happens to manifest when some other handle allocation is attempted (which fails due to exhaustion).

**Comment by bdemers** [comment]
That would be my guess, but it does seem odd that multiple people have reported it.
It's possible both were on the edge, and then the ServiceLoader usage pushed it over.

@mrwilby did fixing your handle leak resolve this issue for you?

**Comment by lhazlewood** [comment]
There could be a file handle leak in application code, sure, but it could also just be the volume of calls to `ServiceLoader`.

I personally would expect `ServiceLoader` to cache fqcn lookup results so it doesn't have to re-read files again for the same fqcn, but I don't know if it does for sure.  If it does not, and enough calls to create a JWT parser exist (e.g. creating a JwtParser on every http request, instead of creating a JwtParser application singleton, which looks to be the case in the above stack trace), then hundreds or thousands of file I/O attempts could occur over the lifespan of the application (two or three per JwtParser creation).  If that's the case, and the file handles are not closed quickly enough (e.g. cached or scheduled-but-not-closed by the operating system), Amazon's `ulimit` settings just may not be high enough.

#752 will eliminate any file I/O no matter how many (or not) parsers are created, so that should put an end to these issues in these types of transient environments, I would think.
