### ISSUE TITLE
Is there an alternative for parseClaimsJws() in Jwts.builder() for jjwt?

### ISSUE THREAD

**Issue by TheLeaf-code** [jwtk/jjwt#689]
I am not entirely sure if this is a bug or not, so posting here.

Currently following [this][1] documentation to implement Apple sign in on the server side on our Java server. In this documentation, the author is using jjwt in order to verify the jwt token passed in from the client side. I was able to complete all of the steps in here, except for this line of code:

   

    Jwts.parser().setSigningKey(publicKey).parseClaimsJws(idToken).getBody();

I am getting a "'parser()' is deprecated" and "'setSigningKey(java.security.Key)' is deprecated" warning as well as this error when running the command:

    Exception in thread "main" io.jsonwebtoken.lang.UnknownClassException: Unable to load class named [io.jsonwebtoken.io.OrgJsonDeserializer] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.
	at io.jsonwebtoken.lang.Classes.forName(Classes.java:92)
	at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:136)
	at io.jsonwebtoken.impl.io.RuntimeClasspathDeserializerLocator.locate(RuntimeClasspathDeserializerLocator.java:36)
	at io.jsonwebtoken.impl.io.RuntimeClasspathDeserializerLocator.getInstance(RuntimeClasspathDeserializerLocator.java:21)
	at io.jsonwebtoken.impl.io.RuntimeClasspathDeserializerLocator.getInstance(RuntimeClasspathDeserializerLocator.java:12)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:227)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:513)
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:573)
	at main.checkCredentials(main.java:81)
	at main.main(main.java:28)

Process finished with exit code 1

This makes me think that parseClaimsJws is also depreciated. According to [this documentation][3], Jwts.parserBuilder() is what has replaced Jwts.parser() but I cannot seem to find an alternative to parseClaimsJwts(). Is there another way to verify a jwt with jjwt as I have mentioned above?

  [1]: https://developer.apple.com/forums/thread/125731
  [3]: https://github.com/jwtk/jjwt/issues/473

**Comment by bdemers** [comment]
I’m mobile (sorry for the sort reply)

It’s a “builder” pattern so you need to call the “build” method to get the parser, something like:

    Jwts.parserBuilder()
      // set signing keys, and other props
      .build();

The interface parser interface is the same, it’s now immutable.

**Comment by TheLeaf-code** [comment]
@bdemers Hi, thanks for the response. I appreciate the help!
